services:
  koii:
    image: local/koii
    container_name: koii-${NUMBER}
    volumes:
      - "./koii-keys/koii-${NUMBER}/wallet:/root/.config/koii"
      - "./koii-keys/koii-${NUMBER}/namespace:/root/VPS-task/namespace"
      - "./images:/images:ro"
    networks:
      - koii-net
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    runtime: sysbox-runc
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - PROXY=${PROXY}
      - UDP=${UDP}
      - DEFAULT_DNS=${DEFAULT_DNS}
      - INITIAL_STAKING_WALLET_BALANCE=${INITIAL_STAKING_WALLET_BALANCE}
      - TASK_IDS=${TASK_IDS}
      - TASK_STAKES=${TASK_STAKES}
      - NODE_VARS=${NODE_VARS}
      - KOII_IMAGE_VERSION=${KOII_IMAGE_VERSION}
    restart: always


networks:
  koii-net:
    external: true
    name: koii-net-${NETNUMBER}
